Changes to compile on OSX
radiotap/radiotap-library pull request #3
Opened 2018-05-25 14:01 UTC by venkatarun95

In OSX, 'endian.h' is now in 'machine/endian.h' and use 'libkern/OSByteOrder.h'.

Fix is similar to the issue n https://github.com/br101/horst/issues/3

2018-05-25 14:05 UTC, jmberg requested changes

2018-05-25 14:05 UTC, jmberg commented on parse.c
>  #include "radiotap_iter.h"
this seems wrong, you shouldn't move that into the ifdef

2018-05-29 20:51 UTC, venkatarun95 commented
I believe I have addressed your concerns. Please have a look

2018-05-30 09:12 UTC, jmberg approved these changes

2018-05-30 09:13 UTC, merged